package com.apicia.config;

import java.util.ArrayList;
import java.util.List;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

@Component
@ConfigurationProperties(prefix = "endpoint-extraction")
public class EndpointExtractionProperties {

    private boolean enabled = true;
    private boolean startupEnabled = true;
    private boolean analyzeOnStartup = true;
    private boolean failOnStartupError = false;
    private boolean includeExtractorEndpoints = true;
    private String sourceRoot = "src/main/java";
    private String projectId = "api-cia";
    private String version = "local";
    private String title = "api-cia API";
    private String description = "OpenAPI contract generated by static source parsing.";
    private List<String> servers = new ArrayList<>(List.of("/"));

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public boolean isStartupEnabled() {
        return startupEnabled;
    }

    public void setStartupEnabled(boolean startupEnabled) {
        this.startupEnabled = startupEnabled;
    }

    public boolean isAnalyzeOnStartup() {
        return analyzeOnStartup;
    }

    public void setAnalyzeOnStartup(boolean analyzeOnStartup) {
        this.analyzeOnStartup = analyzeOnStartup;
    }

    public boolean isFailOnStartupError() {
        return failOnStartupError;
    }

    public void setFailOnStartupError(boolean failOnStartupError) {
        this.failOnStartupError = failOnStartupError;
    }

    public boolean isIncludeExtractorEndpoints() {
        return includeExtractorEndpoints;
    }

    public void setIncludeExtractorEndpoints(boolean includeExtractorEndpoints) {
        this.includeExtractorEndpoints = includeExtractorEndpoints;
    }

    public String getSourceRoot() {
        return sourceRoot;
    }

    public void setSourceRoot(String sourceRoot) {
        this.sourceRoot = sourceRoot;
    }

    public String getProjectId() {
        return projectId;
    }

    public void setProjectId(String projectId) {
        this.projectId = projectId;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<String> getServers() {
        return servers;
    }

    public void setServers(List<String> servers) {
        this.servers = servers;
    }
}
