package com.apicia.service.sdk;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.parser.OpenAPIParser;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.Operation;
import io.swagger.v3.oas.models.PathItem;
import io.swagger.v3.oas.models.media.MediaType;
import io.swagger.v3.oas.models.media.Schema;
import io.swagger.v3.oas.models.parameters.Parameter;
import io.swagger.v3.oas.models.parameters.RequestBody;
import io.swagger.v3.parser.core.models.SwaggerParseResult;
import org.openapitools.codegen.ClientOptInput;
import org.openapitools.codegen.DefaultGenerator;
import org.openapitools.codegen.config.CodegenConfigurator;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

@Service
public class SdkGeneratorService {

    private final ObjectMapper objectMapper = new ObjectMapper();

    /**
     * Generates a complete client SDK package (e.g. typescript-axios, dart, python, java)
     * from an OpenAPI specification and returns it as a zipped byte array.
     */
    public byte[] generateSdk(String openApiSpec, String language) throws Exception {
        if (openApiSpec == null || openApiSpec.isBlank()) {
            throw new IllegalArgumentException("OpenAPI specification must not be null or blank.");
        }

        String targetLanguage = (language == null || language.isBlank()) ? "typescript-axios" : language.trim().toLowerCase();

        Path tempWorkingDir = Files.createTempDirectory("apicia-sdk-work-");
        Path tempOutputDir = tempWorkingDir.resolve("output");
        Files.createDirectories(tempOutputDir);
        Path specFile = tempWorkingDir.resolve("spec.json");
        Files.writeString(specFile, openApiSpec, StandardCharsets.UTF_8);

        try {
            CodegenConfigurator configurator = new CodegenConfigurator()
                    .setInputSpec(specFile.toAbsolutePath().toString())
                    .setGeneratorName(targetLanguage)
                    .setOutputDir(tempOutputDir.toAbsolutePath().toString());

            ClientOptInput clientOptInput = configurator.toClientOptInput();
            DefaultGenerator generator = new DefaultGenerator();

            generator.opts(clientOptInput).generate();

            return zipFolder(tempOutputDir);
        } finally {
            deleteDirectoryRecursively(tempWorkingDir);
        }
    }

    /**
     * Converts an OpenAPI specification into a Postman Collection v2.1.0 format JSON.
     */
    public Map<String, Object> exportPostmanCollection(String openApiSpec) {
        if (openApiSpec == null || openApiSpec.isBlank()) {
            throw new IllegalArgumentException("OpenAPI specification must not be null or blank.");
        }

        SwaggerParseResult parseResult = new OpenAPIParser().readContents(openApiSpec, null, null);
        OpenAPI openApi = parseResult.getOpenAPI();
        if (openApi == null) {
            throw new IllegalArgumentException("Unable to parse OpenAPI specification.");
        }

        Map<String, Object> postman = new LinkedHashMap<>();

        // 1. Info block
        String title = (openApi.getInfo() != null && openApi.getInfo().getTitle() != null)
                ? openApi.getInfo().getTitle()
                : "APICIA API Collection";
        String description = (openApi.getInfo() != null && openApi.getInfo().getDescription() != null)
                ? openApi.getInfo().getDescription()
                : "Autogenerated Postman Collection from APICIA snapshot.";

        Map<String, Object> info = new LinkedHashMap<>();
        info.put("name", title);
        info.put("description", description);
        info.put("schema", "https://schema.getpostman.com/json/collection/v2.1.0/collection.json");
        info.put("_postman_id", UUID.randomUUID().toString());
        postman.put("info", info);

        // 2. Variables block (e.g. baseUrl)
        List<Map<String, Object>> variables = new ArrayList<>();
        Map<String, Object> baseUrlVar = new LinkedHashMap<>();
        baseUrlVar.put("key", "baseUrl");
        baseUrlVar.put("value", "http://localhost:8080");
        baseUrlVar.put("type", "string");
        variables.add(baseUrlVar);
        postman.put("variable", variables);

        // 3. Group operations into folders by tags or controllers
        Map<String, List<Map<String, Object>>> folderMap = new LinkedHashMap<>();

        if (openApi.getPaths() != null) {
            for (Map.Entry<String, PathItem> pathEntry : openApi.getPaths().entrySet()) {
                String path = pathEntry.getKey();
                PathItem pathItem = pathEntry.getValue();
                if (pathItem == null) continue;

                Map<PathItem.HttpMethod, Operation> ops = pathItem.readOperationsMap();
                for (Map.Entry<PathItem.HttpMethod, Operation> opEntry : ops.entrySet()) {
                    PathItem.HttpMethod httpMethod = opEntry.getKey();
                    Operation op = opEntry.getValue();
                    if (op == null) continue;

                    Map<String, Object> postmanItem = buildPostmanItem(path, httpMethod.name(), op, openApi);

                    String folderName = "Default";
                    if (op.getTags() != null && !op.getTags().isEmpty()) {
                        folderName = op.getTags().get(0);
                    } else if (op.getExtensions() != null && op.getExtensions().containsKey("x-controller-class")) {
                        String fullCtrl = String.valueOf(op.getExtensions().get("x-controller-class"));
                        folderName = fullCtrl.contains(".") ? fullCtrl.substring(fullCtrl.lastIndexOf('.') + 1) : fullCtrl;
                    }

                    folderMap.computeIfAbsent(folderName, k -> new ArrayList<>()).add(postmanItem);
                }
            }
        }

        // 4. Build items list
        List<Map<String, Object>> items = new ArrayList<>();
        for (Map.Entry<String, List<Map<String, Object>>> entry : folderMap.entrySet()) {
            Map<String, Object> folder = new LinkedHashMap<>();
            folder.put("name", entry.getKey());
            folder.put("item", entry.getValue());
            items.add(folder);
        }
        postman.put("item", items);

        return postman;
    }

    public byte[] exportPostmanCollectionBytes(String openApiSpec) throws Exception {
        Map<String, Object> postman = exportPostmanCollection(openApiSpec);
        String json = objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(postman);
        return json.getBytes(StandardCharsets.UTF_8);
    }

    private Map<String, Object> buildPostmanItem(String path, String httpMethod, Operation op, OpenAPI openApi) {
        Map<String, Object> item = new LinkedHashMap<>();
        String name = op.getSummary() != null ? op.getSummary() : (httpMethod + " " + path);
        item.put("name", name);

        Map<String, Object> request = new LinkedHashMap<>();
        request.put("method", httpMethod);

        // Headers
        List<Map<String, Object>> headers = new ArrayList<>();
        headers.add(Map.of("key", "Content-Type", "value", "application/json", "type", "text"));
        headers.add(Map.of("key", "Accept", "value", "application/json", "type", "text"));
        request.put("header", headers);

        // URL construction
        Map<String, Object> url = new LinkedHashMap<>();
        String rawPath = path.startsWith("/") ? path.substring(1) : path;
        url.put("raw", "{{baseUrl}}/" + rawPath);
        url.put("host", List.of("{{baseUrl}}"));
        url.put("path", Arrays.asList(rawPath.split("/")));

        // Query parameters
        if (op.getParameters() != null) {
            List<Map<String, Object>> queryParams = new ArrayList<>();
            for (Parameter p : op.getParameters()) {
                if ("query".equalsIgnoreCase(p.getIn())) {
                    Map<String, Object> q = new LinkedHashMap<>();
                    q.put("key", p.getName());
                    q.put("value", "");
                    q.put("description", p.getDescription() != null ? p.getDescription() : "");
                    queryParams.add(q);
                }
            }
            if (!queryParams.isEmpty()) {
                url.put("query", queryParams);
            }
        }
        request.put("url", url);

        // Request body sample
        RequestBody reqBody = op.getRequestBody();
        if (reqBody != null && reqBody.getContent() != null) {
            MediaType jsonMedia = reqBody.getContent().get("application/json");
            if (jsonMedia != null && jsonMedia.getSchema() != null) {
                Map<String, Object> body = new LinkedHashMap<>();
                body.put("mode", "raw");
                body.put("raw", generateSampleJson(jsonMedia.getSchema(), openApi));
                body.put("options", Map.of("raw", Map.of("language", "json")));
                request.put("body", body);
            }
        }

        item.put("request", request);
        item.put("response", Collections.emptyList());
        return item;
    }

    private String generateSampleJson(Schema<?> schema, OpenAPI openApi) {
        try {
            Map<String, Object> sample = new LinkedHashMap<>();
            Schema<?> targetSchema = schema;
            if (schema.get$ref() != null) {
                String ref = schema.get$ref();
                String schemaName = ref.substring(ref.lastIndexOf('/') + 1);
                if (openApi.getComponents() != null && openApi.getComponents().getSchemas() != null) {
                    targetSchema = openApi.getComponents().getSchemas().get(schemaName);
                }
            }

            if (targetSchema != null && targetSchema.getProperties() != null) {
                for (Map.Entry<String, Schema> prop : targetSchema.getProperties().entrySet()) {
                    String propName = prop.getKey();
                    Schema<?> propSchema = prop.getValue();
                    String type = propSchema.getType() != null ? propSchema.getType() : "string";
                    sample.put(propName, getSampleValueForType(type, propName));
                }
            }
            return objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(sample);
        } catch (Exception e) {
            return "{}";
        }
    }

    private Object getSampleValueForType(String type, String fieldName) {
        return switch (type.toLowerCase()) {
            case "integer", "int" -> 1;
            case "number", "float", "double" -> 99.99;
            case "boolean" -> true;
            case "array" -> Collections.emptyList();
            default -> fieldName.toLowerCase().contains("email") ? "user@example.com" : "string";
        };
    }

    private byte[] zipFolder(Path sourceDirPath) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try (ZipOutputStream zos = new ZipOutputStream(baos)) {
            Files.walk(sourceDirPath)
                    .filter(path -> !Files.isDirectory(path))
                    .forEach(path -> {
                        String relativePath = sourceDirPath.relativize(path).toString().replace('\\', '/');
                        ZipEntry zipEntry = new ZipEntry(relativePath);
                        try {
                            zos.putNextEntry(zipEntry);
                            Files.copy(path, zos);
                            zos.closeEntry();
                        } catch (IOException e) {
                            throw new RuntimeException("Error zipping file: " + path, e);
                        }
                    });
        }
        return baos.toByteArray();
    }

    private void deleteDirectoryRecursively(Path path) {
        if (path != null && Files.exists(path)) {
            try {
                Files.walk(path)
                        .sorted((a, b) -> b.compareTo(a))
                        .map(Path::toFile)
                        .forEach(File::delete);
            } catch (IOException ignored) {
            }
        }
    }
}
